### ISSUE TITLE
MacOS doesn't show imgui interface

### ISSUE THREAD

**Issue by wilsonk** [michal-z/zig-gamedev#52] opened 2022-04-24 09:04 UTC
Hello again Michal,

I just pulled down zig-gamedev (version 2684288794864ab1f59acd40db576b02b00764c4) on Win10 (with a Vega64 card, bottom left), Arch Linux (R9 380 card, bottom right) and an M1 Mac (Big Sur, top right). Everything seemed to build and run fine at first glance (except the error with tests previously mentioned in https://github.com/michal-z/zig-gamedev/issues/51), but then I clued in to the fact that the MacOS version doesn't have any imgui interface for the wgpu examples. Here is a pic of all three running the triangle example:
![Zig-GameDev-MacOS-Linux-Win10](https://user-images.githubusercontent.com/38802/164967663-1543fca4-f649-48d8-93a3-907f063fb933.png)

Perhaps the MacOS version shouldn't have the interface and I just missed it in the docs? Or is this a bug on my machine?

P.S. Also, one small difference I noticed between these three programs is that the Win10 spinning triangles actually stop spinning when I drag the window around...then the spinning starts again after I stop dragging the window around (or even if I just right click on the window header! ). The Arch/Mac triangles continue to spin if I drag the window around. A Win10 quirk with the driver? Not sure...and not a big deal, I am just mentioning it as a curiosity.

**Comment by michal-z** [comment] 2022-04-24 09:21
MacOS version should have imgui interface. Unfortunately I don't have MacOS machine to properly test it but I got report that interface is there on MacOS, see: https://discord.com/channels/605571803288698900/964863116296994926/964960941567541269

Can you try `procedural_mesh_wgpu` sample?

On Windows, dragging (and resizing) the window blocks normal processing so this is normal behavior on this OS. We could fix this by spawning a worker thread and doing all rendering in it. I will probably do this in the future.

**Comment by wilsonk** [comment] 2022-04-24 09:48
Yes, I saw that comment from rudedogg (actually that was part of the reason I tried the examples on my Mac), but I am not sure which OS version/arch he is running on. I have posted a quick question in that thread to see if he can enlighten me.

I actually tried both the triangle and procedural examples with the same results on all three machines...ie. the Mac has no imgui interface for either the triangle or procedural wgpu examples, but the other machines work fine.

I figured the Windows issue may be something like that, but I also thought it might be my drivers or a simple DirectX switch that could be supplied in the example code. Silly MS :)

**Comment by timcash** [comment] 2022-04-24 11:47
No gui for me on macbook air m1 v12.3. I'll see if I can offer more insight.

**Comment by michal-z** [comment] 2022-04-24 12:27
Thanks for the info, looks like a regression in Dawn. Is there a Renderdoc or something similar for Metal? Yeah, would be great if you could see what's happening there.

**Comment by timcash** [comment] 2022-04-24 13:06
These are new areas for me. To verify my understanding ( Webgpu -> dawn -> Apple Metal ) the renderdoc on apple metal would point to a debugging strategy?

**Comment by michal-z** [comment] 2022-04-24 13:13
Yes, your understanding is correct.
We use standard WebGPU imgui renderer: https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_wgpu.cpp

Renderdoc on Metal could show you the GPU state, shaders and drawcalls that the imgui renderer is doing. This info could give as an idea why the result of the drawcalls don't show up on the screen.

**Comment by michal-z** [comment] 2022-04-24 13:20
@timcash @wilsonk I did a small change regarding gui renderer. Can you please re-test?

**Comment by timcash** [comment] 2022-04-24 14:04
<img width="1251" alt="Screen Shot 2022-04-24 at 9 04 02 AM" src="https://user-images.githubusercontent.com/118253/164980317-2c4091bd-1f78-44ad-be30-0deec8172660.png">

**Comment by timcash** [comment] 2022-04-24 14:20
I am starting by using these links.
Dawn -> OS bugs
https://bugs.chromium.org/p/dawn/issues/list?q=OS%3DmacOS&can=2
Metal Dev Docs for debugger in xcode. I would need to compile zig-gamedev in Xcode?
https://developer.apple.com/documentation/metal/debugging_tools/viewing_your_gpu_workload_with_the_metal_debugger

**Comment by michal-z** [comment] 2022-04-24 14:35
I have never used MacOS in my life :)
But, I don't think you need to compile zig-gamedev in xcode, try to just open/load the binary in xcode.

**Comment by timcash** [comment] 2022-04-24 19:07
<img width="1282" alt="Screen Shot 2022-04-24 at 2 05 34 PM" src="https://user-images.githubusercontent.com/118253/164992400-88330a5a-c54c-4357-9e4e-990df38acb11.png">
Some of what I see. 
I see this warning about a texture not being used.
<img width="869" alt="Screen Shot 2022-04-24 at 2 07 18 PM" src="https://user-images.githubusercontent.com/118253/164992466-ae4c7ccd-1fcf-42b7-9e53-763fd59c252e.png">

**Comment by kamidev** [comment] 2022-04-24 19:09
Hi! The imgui interface doesn't show up on my M1 Mac either. I just re-cloned the repo to make sure I had no cache issues.
➜  zig-gamedev git:(main) zig version
0.10.0-dev.1929+963ac6091
➜  zig-gamedev git:(main) zig build procedural_mesh_wgpu-run
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1 Max
[zgpu]   Driver: Metal driver on macOS Version 12.3.1 (Build 21E258)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal

**Comment by kamidev** [comment] 2022-04-24 19:11
@timcash How did you setup your gputrace?

**Comment by michal-z** [comment] 2022-04-24 20:25
@timcash Nice progress! 512x256 RGBAUnorm texture is a font that should be used by imgui. Please try to find a drawcall that uses that texture.

You should be able to "step" through drawcalls and see what each drawcall adds to the image. The last drawcall is the gui.

**Comment by timcash** [comment] 2022-04-25 00:18
<img width="1440" alt="Screen Shot 2022-04-24 at 7 17 36 PM" src="https://user-images.githubusercontent.com/118253/165002850-696b5f6c-d04e-44c0-957c-71e6710c6e00.png">
that texture is solid white in the preview

**Comment by timcash** [comment] 2022-04-25 01:17
<img width="1273" alt="Screen Shot 2022-04-24 at 8 15 27 PM" src="https://user-images.githubusercontent.com/118253/165005631-ab9b3fba-8aa0-408e-8e27-ef7b895c1265.png">
found a way to start looking at more detail.

Would dawn's test cover this in some way? so many menus in GPU debuggers... menus everywhere

**Comment by michal-z** [comment] 2022-04-25 16:02
There should be two render passes, first for all the geometry and the second one for the gui.
In geometry pass there should be 11 draw calls.
In gui pass there should be two draw calls (white solid texture is fine, I see the same on WIndows in PIX).

![image](https://user-images.githubusercontent.com/11540112/165128111-b3d78ddc-d740-4ed0-8252-11d315afc204.png)

**Comment by timcash** [comment] 2022-04-25 17:43
<img width="1270" alt="Screen Shot 2022-04-25 at 12 42 43 PM" src="https://user-images.githubusercontent.com/118253/165144160-32531539-cca2-48ad-b2a0-5becf4a45a62.png">
Ill try that next. Here is the second draw call I think

**Comment by michal-z** [comment] 2022-04-25 17:57
Yes, this looks like a second render pass (gui). Is there a call to `drawIndexedPrimitives()` in this second render pass (there should be 2 such calls)?

**Comment by michal-z** [comment] 2022-04-25 18:55
Strange. Can you comment out first render pass (geometry) and draw only gui? You will need to change `load_op` from '.load' to `.clear` on line 296.

**Comment by wilsonk** [comment] 2022-04-25 20:36
I quickly tried changing the gui ```load_op``` to ```.clear``` on Linux and my M1. The gui works on Linux but didn't show up on the M1.

**Comment by michal-z** [comment] 2022-04-26 09:00
At this point I think it would be best to use normal CPU debugger and step into `zgpu.gui.draw(pass)`. Two draw calls should be issued from there.

Also, @timcash looks like there are some warnings (purple triangles with !) reported by GPU debugger - is there more info about them?

**Comment by michal-z** [comment] 2022-04-26 17:58
On MacOS you should probably use xcode or vs code.

**Comment by kamidev** [comment] 2022-04-26 18:51
GDB doesn't work on M1 Mac. But XCode comes with LLDB, which does work and is what Apple prefers. See https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/gdb_to_lldb_transition_guide/document/lldb-command-examples.html#//apple_ref/doc/uid/TP40012917-CH3-SW1. 

For actual debugging, I think VS Code is easier to work with. Here is a recipe for debugging Zig using VS Code: https://dev.to/watzon/debugging-zig-with-vs-code-44ca.

**Comment by kamidev** [comment] 2022-04-26 18:58
To use the recipe for stepping through the "procedural_mesh_wgpu" code, first make some small changes to "tasks.json" and "launch.json". This worked for me. Obviously, your path to the exe will be different:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "type": "shell",
      "command": "zig build",
      "problemMatcher": [],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "/Users/jonas/src/zig/zig-gamedev/zig-out/bin/procedural_mesh_wgpu",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "preLaunchTask": "build",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}
```

**Comment by timcash** [comment] 2022-04-26 19:41
<img width="1026" alt="Screen Shot 2022-04-26 at 2 40 46 PM" src="https://user-images.githubusercontent.com/118253/165379305-80d4b5af-1c2b-43bc-82f1-dcfd59ed2e97.png">
got LLDB going

**Comment by timcash** [comment] 2022-04-26 20:14
<img width="1438" alt="Screen Shot 2022-04-26 at 3 13 53 PM" src="https://user-images.githubusercontent.com/118253/165384409-d4f1863b-4a6b-4dc2-bde4-b199c10e6e69.png">
I see some comments about errors here :)

**Comment by timcash** [comment] 2022-04-26 21:03
It steps through all the code, what am I looking for?

**Comment by michal-z** [comment] 2022-04-26 21:39
You can build Dawn from source and try to understand what the error is:
`zig build procedural_mesh_wgpu -Ddawn-from-source=true`
You will be able to step into `wgpuQueueWriteBuffer`.

This call should copy vertex data from CPU to GPU, looks like this code errors out on M1 and data is not copied.

**Comment by michal-z** [comment] 2022-04-27 14:36
Set `minimal_debug_symbols` to `false` (`libs/mach-gpu-dawn/build.zig` line 71).

**Comment by timcash** [comment] 2022-04-27 21:24
<img width="1440" alt="Screen Shot 2022-04-27 at 4 21 50 PM" src="https://user-images.githubusercontent.com/118253/165633528-52cf0705-b682-491f-901a-b1171e6fd541.png">
this buffer is invalid? does not look good.

**Comment by timcash** [comment] 2022-04-27 21:26
<img width="1439" alt="Screen Shot 2022-04-27 at 4 26 16 PM" src="https://user-images.githubusercontent.com/118253/165633855-f6eed480-6c4f-4eac-94c5-820a12957ef2.png">
may have been optimized out?

**Comment by michal-z** [comment] 2022-04-27 21:51
I think it is optimized out.

But, I've noticed this:
size_copy_: 0
in Terminal window.

This is suspicious, there are 3 copy operations (in order):
- vertex buffer data (CPU -> GPU)
- index buffer data (CPU -> GPU)
- uniform buffer data (CPU -> GPU)

The third copy size should be 64 bytes, why is it 0?

**Comment by timcash** [comment] 2022-04-27 22:22
the size_copy_ is mine from debugging yeah, Ill take a look. trying to find uniform. Will it help to print out the size?

**Comment by timcash** [comment] 2022-04-27 22:32
<img width="1440" alt="Screen Shot 2022-04-27 at 5 32 02 PM" src="https://user-images.githubusercontent.com/118253/165642147-31c3b016-2c0b-4fbc-978f-fc2b8a540a50.png">
is this helpful?

**Comment by michal-z** [comment] 2022-04-28 10:07
Thanks for your work.

Unfortunately I still don't know what's going on. Is Dawn hitting/reporting an error when you step through code?

**Comment by michal-z** [comment] 2022-04-28 21:16
@timcash I would suggest stepping into `wgpuRenderPassEncoderDrawIndexed` line 455 in `imgui_impl_wgpu.cpp` and looking for an error.

I think that the second draw call fails and this is why we can't see it in GPU debugger.

**Comment by timcash** [comment] 2022-04-29 17:32
<img width="883" alt="Screen Shot 2022-04-29 at 12 32 32 PM" src="https://user-images.githubusercontent.com/118253/165994379-2f1b0947-5db6-4be9-b345-6172d8bb2c93.png">
I see nullptr errors like this

**Comment by timcash** [comment] 2022-04-29 17:33
Oh now I see this
```
// The interface of Result<T, E> should look like the following.
//  public:
//    Result(T&& success);
//    Result(std::unique_ptr<E> error);
//
//    Result(Result<T, E>&& other);
//    Result<T, E>& operator=(Result<T, E>&& other);
//
//    ~Result();
//
//    bool IsError() const;
//    bool IsSuccess() const;
//
//    T&& AcquireSuccess();
//    std::unique_ptr<E> AcquireError();

// Specialization of Result for returning errors only via pointers. It is basically a pointer
// where nullptr is both Success and Empty.
```

**Comment by timcash** [comment] 2022-04-29 17:37
<img width="973" alt="Screen Shot 2022-04-29 at 12 36 41 PM" src="https://user-images.githubusercontent.com/118253/165994947-9f468832-efd2-446b-bd6d-e4cadb2797ec.png">
"this" with invalid address

**Comment by timcash** [comment] 2022-04-29 17:40
<img width="1041" alt="Screen Shot 2022-04-29 at 12 39 21 PM" src="https://user-images.githubusercontent.com/118253/165995402-25f4da47-039c-4d28-bad1-91824d25a352.png">
"self" becomes "this" on line 120 in `RenderEncoderBase.cpp`?

**Comment by michal-z** [comment] 2022-04-29 17:55
This looks like some optimized out values. Notice that this is the common code used also on Windows and Linux so it should work fine. I would expect an error on a lower-level in Metal backend. Step into lower layers until you find actual Metal draw call.

**Comment by timcash** [comment] 2022-04-29 17:55
<img width="1049" alt="Screen Shot 2022-04-29 at 12 54 37 PM" src="https://user-images.githubusercontent.com/118253/165997522-44a1e7f8-ced2-41c1-a097-53250548874a.png">
I also see could not evaluate DW_OP_entry_value

**Comment by timcash** [comment] 2022-04-29 19:34
stepping though for an hour. nothing so far.

**Comment by michal-z** [comment] 2022-04-29 20:54
@timcash @wilsonk @kamidev Can you fetch the latest code and re-test?

**Comment by kamidev** [comment] 2022-04-30 02:16
Re-tested the latest code on M1, using zig 0.10.0-dev.2016+0e49142ce, and have some good news and some bad news. :-) 

The latest code didn't run for me without a small change to "libs/zmath/src/zmath.zig". 

```
-    var temp: f32 = math.fabs(angle);
+    var temp: f32 = @fabs(angle);
```

As @wilsonk noted in https://github.com/michal-z/zig-gamedev/issues/51 , Zig just [reorganized compiler_rt_math functions](https://github.com/ziglang/zig/commit/360ecc1a2f72967f3a3882b3327e130bdc4e18c0). Mach has problems with this right now, too. Probably not very hard to fix, but still a breaking change.

**Comment by kamidev** [comment] 2022-04-30 02:17
There is still no imgui interface for the mesh example. But triangle_wgpu now displays a read-only menu.
 ﻿﻿
![image](https://user-images.githubusercontent.com/1655/166085583-d61bc7dc-6b83-4ded-94b5-720068bd602f.png)

**Comment by wilsonk** [comment] 2022-04-30 07:04
I get the same result: no gui for mesh but there is one for triangle example

**Comment by michal-z** [comment] 2022-04-30 07:21
That's super strange, because both samples use the same code.
Could you try to remove Zig cache and rebuild? Maybe it's some Zig caching issue...

**Comment by wilsonk** [comment] 2022-04-30 07:41
Removed all caches in local dir and ~/.cache/zig and the procedural_mesh example still has no gui...very strange

**Comment by michal-z** [comment] 2022-04-30 07:56
I have one more idea will submit a potential fix later today.

**Comment by michal-z** [comment] 2022-04-30 09:00
Please try now.

**Comment by kamidev** [comment] 2022-04-30 09:28
Sorry. Doesn't work for me. 

![image](https://user-images.githubusercontent.com/1655/166100031-0f692450-7af8-4461-ad05-e75cd9e18ba1.png)

**Comment by kamidev** [comment] 2022-04-30 09:29
I tried on an Intel Macbook Pro 2019. It works there: 

![image](https://user-images.githubusercontent.com/1655/166100085-98a07f0e-979a-4682-b277-59bbbd443913.png)

**Comment by kamidev** [comment] 2022-04-30 09:33
I appreciate your efforts. Let me know if I can test anything else later today.

**Comment by timcash** [comment] 2022-04-30 14:57
Took an hour to step through the code. 15 years ago I last used C++ but starting to get familiar with the tooling and syntax again.

**Comment by michal-z** [comment] 2022-04-30 16:41
@kamidev Gui in `triangle_wgpu` should be fully interactable - is this the case on macos?

**Comment by michal-z** [comment] 2022-04-30 16:51
Can you please re-test one more time?

**Comment by kamidev** [comment] 2022-04-30 19:23
Sorry, the new fix doesn't work for the mesh example. And as far as I can tell, the triangle_wgpu GUI is not interactable at all on M1.

I'll be offline for a few hours but will check in here and on Discord later.

**Comment by michal-z** [comment] 2022-04-30 21:54
I did a potential fix for not interactable GUI in `triangle_wgpu`.

**Comment by kamidev** [comment] 2022-04-30 22:50
Yes! Triangle_wgpu has a working GUI interface on M1 now.

**Comment by kamidev** [comment] 2022-04-30 22:54
Still no GUI for the mesh example, unfortunately.

**Comment by wilsonk** [comment] 2022-04-30 23:19
Can confirm the triangle example GUI works here. Still no GUI showing up for the procedural_mesh example...so strange.

**Comment by michal-z** [comment] 2022-05-01 07:35
It would be worth trying to comment out/modify first pass (geometry pass) until GUI works.
For example, we could try to remove all draw calls from the first pass and leave only clear operation.
It looks like first pass generates an error internally and causes GUI not to draw.

**Comment by wilsonk** [comment] 2022-05-01 23:44
Cleaned caches and rebuilt/reran...procedural example gui still doesn't work. Ugh. Triangle example gui still works.

**Comment by kamidev** [comment] 2022-05-02 15:41
Latest zig and zig-gamedev code, clean caches. Same as for@wilsonk: triangle gui still works, mesh gui doesn't show up. Sucks! Will do some step-by-step uncommenting later and report back.

**Comment by michal-z** [comment] 2022-05-05 09:55
Hi guys, we now use uniform buffer pool to upload data to the GPU. Can you please re-test both demos?

**Comment by wilsonk** [comment] 2022-05-05 13:40
Hmm, very strange here. Both examples build fine here with that same zig compiler on my M1 as @kamidev  is using? Not sure what is going on there. (I built with artifacts in the cache and then cleaned everything and did it again with these same results).

Unfortunately, both examples fail intermittently with this:

```
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1
[zgpu]   Driver: Metal driver on macOS Version 11.6.5 (Build 20G527)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal
thread 2077080 panic: reached unreachable code
/Users/wilsonk/Downloads/zig/build/lib/zig/std/debug.zig:260:14: 0x1008019bf in std.debug.assert (procedural_mesh_wgpu)
    if (!ok) unreachable; // assertion failure
             ^
/Users/wilsonk/zig-gamedev/libs/zgpu/src/zgpu.zig:258:15: 0x1008179ff in .zgpu.GraphicsContext.uniformsNextStagingBuffer (procedural_mesh_wgpu)
        assert(gctx.uniforms.stage.num < uniforms_staging_pipeline_len);
              ^
/Users/wilsonk/zig-gamedev/libs/zgpu/src/zgpu.zig:322:39: 0x10081cf6f in .zgpu.GraphicsContext.submit (procedural_mesh_wgpu)
        gctx.uniformsNextStagingBuffer();
                                      ^
/Users/wilsonk/zig-gamedev/samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig:623:20: 0x10080be1b in draw (procedural_mesh_wgpu)
    if (gctx.submit(&.{commands}) == .swap_chain_resized) {
                   ^
/Users/wilsonk/zig-gamedev/samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig:693:13: 0x1008095fb in main (procedural_mesh_wgpu)
        draw(&demo);
            ^
/Users/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:581:37: 0x10082b7df in std.start.callMain (procedural_mesh_wgpu)
            const result = root.main() catch |err| {
                                    ^
/Users/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:515:12: 0x10080c693 in std.start.callMainWithArgs (procedural_mesh_wgpu)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/Users/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:480:12: 0x10080c5bf in std.start.main (procedural_mesh_wgpu)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0x18bc3942f in ??? (???)
???:?:?: 0x0 in ??? (???)
The following command terminated unexpectedly:
cd /Users/wilsonk/zig-gamedev && /Users/wilsonk/zig-gamedev/zig-out/bin/procedural_mesh_wgpu

```

When the triangle example does load successfully then the GUI is there and functional, but when the procedural example loads it still doesn't have the GUI!?!? Ugh.

**Comment by kamidev** [comment] 2022-05-05 14:15
Thanks @wilsonk! Good to know you can still build. My local toolchain has been pretty stable and Zig master is moving really fast right now. So my initial guess was a breaking change upstream. Well, I'll figure it out.

BTW, do you see any pattern for the intermittent failures? How frequent are they? Does it seem like you can trigger them by doing something?

**Comment by wilsonk** [comment] 2022-05-05 14:52
No real pattern here. I can run the triangle binary in the zig-out directory and it may work or it may crash...sometimes it works twice and then crashes once, or works three times in a row and then alternates run/crash for a dozen tries...then crash three times in a row!??? Must be a race condition of some sort, I suppose.

**Comment by michal-z** [comment] 2022-05-05 15:49
Yeah, looks like a race condition with async buffer mapping. Can't unfortunately repro this on Windows and Linux.
@wilsonk Do you observe those crashes on all OSes?

**Comment by michal-z** [comment] 2022-05-05 16:54
Please re-test.

**Comment by wilsonk** [comment] 2022-05-06 05:14
Cleaned caches, rebuilt both examples and...woohoo the GUI finally shows up in both examples...HOWEVER they both still crash intermittently!!?! Ugh. 

Actually they both crash much more than they run now (7-8 attempts before it runs once! I thought they weren't going to run at all!). But at least the GUI is there when it does run.

Linux/Win have no problems with either example.

**Comment by michal-z** [comment] 2022-05-06 10:05
Can you try now?

**Comment by michal-z** [comment] 2022-05-06 11:02
Do you see both GUI windows in `procedural mesh (wgpu)`? The first one is non-movable and located in the upper left corner the second one is standard imgui demo window.

**Comment by michal-z** [comment] 2022-05-06 11:16
So, that's still an issue - this small non-movable window is not being drawn.

**Comment by michal-z** [comment] 2022-05-06 12:48
Two changes:
* faster/better fix for crashes
* bigger and more standard GUI (imgui demo window removed)

**Comment by kamidev** [comment] 2022-05-06 14:42
Almost there! Building zig-gamedev successfully again, using zig version: 0.10.0-dev.2103+ac1aaec9c

Triangle sample works and seems to be fully interactive. 
Mesh sasmple looks good, same as for @michal-z. But interaction doesn't work yet.

```
// Open and close demo without doing anything
// No crash but error message afterwards

➜  zig-gamedev git:(main) zig build procedural_mesh_wgpu-run
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1 Max
[zgpu]   Driver: Metal driver on macOS Version 12.3.1 (Build 21E258)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal
[zgpu] Failed to map buffer
[zgpu] Failed to map buffer
```

```
// Trying to close the imgui window causes immediate crash

➜  zig-gamedev git:(main) zig build procedural_mesh_wgpu-run
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1 Max
[zgpu]   Driver: Metal driver on macOS Version 12.3.1 (Build 21E258)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal
Assertion failed: ((g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"), function ErrorCheckEndFrameSanityChecks, file imgui.cpp, line 7984.
The following command terminated unexpectedly:
cd /Users/jonas/src/zig/zig-gamedev && /Users/jonas/src/zig/zig-gamedev/zig-out/bin/procedural_mesh_wgpu
error: the following build command failed with exit code 1:
/Users/jonas/src/zig/zig-gamedev/zig-cache/o/0084f4c951b7e5690edb86549f24cea2/build /Users/jonas/src/zig/zig/build/stage1/bin/zig /Users/jonas/src/zig/zig-gamedev /Users/jonas/src/zig/zig-gamedev/zig-cache /Users/jonas/.cache/zig procedural_mesh_wgpu-run
```

**Comment by michal-z** [comment] 2022-05-06 15:23
I think that now everything should work expect those errors about buffer mapping.

**Comment by kamidev** [comment] 2022-05-06 15:41
Yes, I've tested on both M1 and an Intel Mac now. Seems functional and doesn't crash. Still error messages after closing, though. 

```
➜  zig-gamedev git:(main) stage1 build procedural_mesh_wgpu-run
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1 Max
[zgpu]   Driver: Metal driver on macOS Version 12.3.1 (Build 21E258)
[zgpu]   Adapter type: Discrete GPU
[zgpu]   Backend type: Metal
[zgpu] Window has been resized to: 1776x1042 pixels (888x521 units)
[zgpu] Window has been resized to: 1138x1000 pixels (569x500 units)
[zgpu] Window has been resized to: 1266x1100 pixels (633x550 units)
[zgpu] Failed to map buffer
[zgpu] Failed to map buffer
```

**Comment by michal-z** [comment] 2022-05-06 16:27
Can you confirm that GUI text color is green?

**Comment by kamidev** [comment] 2022-05-06 17:13
Still blue for me, sorry.

**Comment by kamidev** [comment] 2022-05-06 18:02
On M1: right color but wrong place. Impossible to move to the window
On Intel Mac: right color, right place. Impossible to move window, but can minimize it.

**Comment by michal-z** [comment] 2022-05-06 19:04
Latest commit should fix GUI element positions but it will break interaction on MacOS M1 (will be fixed soon), cna you confirm this? M1 macos and Intel macos should look the same.

**Comment by wilsonk** [comment] 2022-05-06 19:32
On my M1, after cleaning caches, both examples run build/fine. The triangle example has a blue GUI near the middle of the screen that is resizable and accepts input (the same as on Linux), however...the procedural example has the smaller GUI showing, but it is slightly off the top of the screen in the upper left corner, as per the picture just above this comment.

**Comment by kamidev** [comment] 2022-05-06 20:32
On M1: right color but still wrong place. Just a sliver of the window is showing in the top right corner. Hard to tell if interaction works, there is almost nothing to click on.

On Intel Mac: right color, right place. Mouse coordinates seem off. But clicking the top left corner of the imgui window works.

**Comment by michal-z** [comment] 2022-05-06 20:59
I think that `imgui.ini` file needs to be deleted after rebuilding.

**Comment by kamidev** [comment] 2022-05-06 21:21
I tried your latest commit, deleted ingui.ini and cleaned caches. 

Still wrong GUI position on M1. Not sure about interaction on Intel, but feels a bit off. Buffer map error messages remain on both M1 and Intel.

**Comment by kamidev** [comment] 2022-05-08 07:45
Yes! Now it works. The imgui window is still partially invisible on startup. But you can move it down and it works. 

![image](https://user-images.githubusercontent.com/1655/167286748-284c5a18-1daf-4105-bc24-af5317a2bd46.png)

![image](https://user-images.githubusercontent.com/1655/167286754-0eba4fa0-b1ca-4cea-859b-8f1a72850c39.png)

**Comment by kamidev** [comment] 2022-05-08 07:46
I am still on Discord, let's continue there.

**Comment by wilsonk** [comment] 2022-05-08 10:12
They both work well here (I was having a little mouse slowness before, but I have a very specialized setup so I just assumed it was my problem...seems to be fine now). Same issue with the procedural example, but at least one can grab the GUI element and drag it more onto the viewable surface.

**Comment by michal-z** [comment] 2022-05-08 10:38
Yes, this is the best we can get for now. Wrong GUI position seems to be problem related to Zig + AArch64 + macos. Let's leave the issue open and wait for upstream fixes.

**Comment by kamidev** [comment] 2022-05-08 23:14
@michal-z Sounds good! I am tracking AArch64 + macos stuff upstream anway. Let's re-test the initial GUI position thing when there are promising changes.

BTW, your last commit fixed the buffer mapping errors on exit. For both M1 and Intel Mac.

**Comment by wilsonk** [comment] 2022-05-10 18:56
Yep, it looks good here now also.

**Comment by michal-z** [comment] 2022-05-10 20:20
That's great! I'm closing it. Thanks for your help guys to resolve this.

**Closed by michal-z** 2022-05-10 20:20 UTC
